# Data Sources Configuration
# =========================
# 
# Centralized configuration for all data sources across states
# Includes primary sources, fallbacks, and update frequencies

states:
  wisconsin:
    name: "Wisconsin"
    fips_code: "55"
    
    business_registrations:
      primary:
        name: "Wisconsin Department of Financial Institutions"
        url: "https://apps.dfi.wi.gov/apps/corpsearch/search.aspx"
        search_endpoint: "https://apps.dfi.wi.gov/apps/corpsearch/Results.aspx"
        type: "web_scraping"
        format: "html"
        update_frequency: "weekly"
        rate_limit: "5_requests_per_minute"
        lookback_days: 90
        target_counties:
          # All 72 Wisconsin Counties
          - "Adams"
          - "Ashland"
          - "Barron"
          - "Bayfield"
          - "Brown"      # Green Bay
          - "Buffalo"
          - "Burnett"
          - "Calumet"
          - "Chippewa"
          - "Clark"
          - "Columbia"
          - "Crawford"
          - "Dane"       # Madison
          - "Dodge"
          - "Door"
          - "Douglas"
          - "Dunn"
          - "Eau Claire"
          - "Florence"
          - "Fond du Lac"
          - "Forest"
          - "Grant"
          - "Green"
          - "Green Lake"
          - "Iowa"
          - "Iron"
          - "Jackson"
          - "Jefferson"
          - "Juneau"
          - "Kenosha"
          - "Kewaunee"
          - "La Crosse"
          - "Lafayette"
          - "Langlade"
          - "Lincoln"
          - "Manitowoc"
          - "Marathon"
          - "Marinette"
          - "Marquette"
          - "Menominee"
          - "Milwaukee"
          - "Monroe"
          - "Oconto"
          - "Oneida"
          - "Outagamie"
          - "Ozaukee"
          - "Pepin"
          - "Pierce"
          - "Polk"
          - "Portage"
          - "Price"
          - "Racine"
          - "Richland"
          - "Rock"       # Janesville
          - "Rusk"
          - "Saint Croix"
          - "Sauk"
          - "Sawyer"
          - "Shawano"
          - "Sheboygan"
          - "Taylor"
          - "Trempealeau"
          - "Vernon"
          - "Vilas"
          - "Walworth"
          - "Washburn"
          - "Washington"
          - "Waukesha"
          - "Waupaca"
          - "Waushara"
          - "Winnebago"   # Appleton
          - "Wood"
        target_business_types:
          food_beverage:
            naics_codes: ["722", "445", "312"]
            keywords: ["restaurant", "pizza", "cafe", "coffee", "bar", "pub", "brewery", "bakery", "deli", "grill", "bistro", "tavern"]
          retail:
            naics_codes: ["441", "442", "443", "444", "445", "446", "447", "448", "451", "452", "453", "454"]
            keywords: ["store", "shop", "retail", "gas station", "convenience", "market", "boutique", "outlet"]
          personal_services:
            naics_codes: ["812", "811"]
            keywords: ["salon", "spa", "barber", "nail", "dry clean", "laundry", "auto repair", "mechanic", "garage"]
          fitness_recreation:
            naics_codes: ["713", "511"]
            keywords: ["gym", "fitness", "yoga", "theater", "cinema", "bowling", "arcade", "recreation"]
          hospitality_care:
            naics_codes: ["721", "624"]
            keywords: ["hotel", "motel", "inn", "child care", "daycare", "senior care", "assisted living"]
        
      fallback:
        name: "Wisconsin Secretary of State"
        url: "https://www.sos.state.wi.us/Pages/Corporations/default.aspx"
        type: "web_scraping"
        format: "html"
        
    sba_loans:
      primary:
        name: "SBA FOIA Data - 7(a) Recent"
        url: "https://data.sba.gov/dataset/0ff8e8e9-b967-4f4e-987c-6ac78c575087/resource/186eb176-b53e-4cbe-ab93-e5c4fb50197d/download/foia-7a-fy2000-fy2009-asof-250331.csv"
        type: "file_download"
        format: "csv"
        update_frequency: "quarterly"
        filter_state: "WI"
      
      secondary:
        name: "SBA FOIA Data - 504 Current"
        url: "https://data.sba.gov/dataset/0ff8e8e9-b967-4f4e-987c-6ac78c575087/resource/4ad7f0f1-9da6-4d90-8bdb-89a6f821a1a9/download/foia-504-fy2010-present-asof-250331.csv"
        type: "file_download"
        format: "csv"
        update_frequency: "quarterly"
        filter_state: "WI"
        
      fallback:
        name: "SBA District Office 5"
        contact: "wisconsin.district@sba.gov"
        type: "manual_request"
        
    business_licenses:
      milwaukee:
        name: "Milwaukee License Search"
        url: "https://itmdapps.milwaukee.gov/LiraPublic/search.jsp"
        search_endpoint: "https://itmdapps.milwaukee.gov/LiraPublic/search.jsp"
        type: "web_scraping"
        format: "html"
        update_frequency: "weekly"
        rate_limit: "5_requests_per_minute"
        
      madison:
        name: "Madison Open Data"
        url: "https://data-cityofmadison.opendata.arcgis.com/"
        api_endpoint: "https://data-cityofmadison.opendata.arcgis.com/api/feed/dcat-ap/1.1.json"
        type: "api"
        format: "json"
        update_frequency: "weekly"
        
      green_bay:
        name: "Green Bay Business Licenses"
        url: "https://www.greenbaywi.gov/387/Business-License"
        type: "web_scraping"
        format: "html"
        
    economic_data:
      primary:
        name: "Wisconsin Economic Development Corporation"
        url: "https://wedc.org/export/data/"
        type: "file_download"
        format: "json"
        
    demographics:
      census_acs:
        name: "U.S. Census Bureau - American Community Survey 5-Year"
        api_base: "https://api.census.gov/data/2022/acs/acs5"
        api_key_required: true
        api_key_url: "https://api.census.gov/data/key_signup.html"
        type: "api"
        format: "json"
        update_frequency: "annual"
        release_schedule: "september"
        rate_limit: "unlimited_reasonable_use"
        documentation: "https://www.census.gov/data/developers/data-sets/acs-5year.html"
        
        geographic_levels:
          - name: "block_group"
            code: "150" 
            description: "Most detailed geographic level (600-3000 people)"
            coverage: "wisconsin_counties"
          - name: "tract"
            code: "140"
            description: "Census tract level (1200-8000 people)"
            coverage: "wisconsin_counties"
          - name: "county"
            code: "050"
            description: "County level"
            coverage: "all_wisconsin"
            
        target_variables:
          population:
            - variable: "B01003_001E"
              name: "total_population"
              description: "Total Population"
            - variable: "B01002_001E" 
              name: "median_age"
              description: "Median Age"
            - variable: "B25001_001E"
              name: "total_housing_units"
              description: "Total Housing Units"
              
          economic:
            - variable: "B19013_001E"
              name: "median_household_income"
              description: "Median Household Income (Past 12 Months)"
            - variable: "B23025_005E"
              name: "unemployment_count"
              description: "Unemployed Population"
            - variable: "B23025_002E"
              name: "labor_force"
              description: "Total Labor Force"
              
          education:
            - variable: "B15003_022E"
              name: "bachelor_degree_count"
              description: "Bachelor's Degree"
            - variable: "B15003_001E"
              name: "total_education_pop"
              description: "Total Population 25+ (Education Universe)"
              
          housing:
            - variable: "B25003_002E"
              name: "owner_occupied_units"
              description: "Owner Occupied Housing Units"
            - variable: "B25003_001E"
              name: "total_occupied_units"
              description: "Total Occupied Housing Units"
              
          transportation:
            - variable: "B08303_001E"
              name: "total_commuters"
              description: "Total Commuters"
            - variable: "B08303_013E"
              name: "commute_60_plus_min"
              description: "Commute 60+ Minutes"
            - variable: "B08301_010E"
              name: "public_transport_count"
              description: "Public Transportation Users"
            - variable: "B08301_001E"
              name: "total_transport_pop"
              description: "Total Transportation Population"
              
        wisconsin_counties:
          # Target Wisconsin counties for demographic analysis
          target_fips_codes:
            - "55001"  # Adams
            - "55003"  # Ashland
            - "55005"  # Barron
            - "55007"  # Bayfield
            - "55009"  # Brown (Green Bay)
            - "55011"  # Buffalo
            - "55013"  # Burnett
            - "55015"  # Calumet
            - "55017"  # Chippewa
            - "55019"  # Clark
            - "55021"  # Columbia
            - "55023"  # Crawford
            - "55025"  # Dane (Madison)
            - "55027"  # Dodge
            - "55029"  # Door
            - "55031"  # Douglas
            - "55033"  # Dunn
            - "55035"  # Eau Claire
            - "55037"  # Florence
            - "55039"  # Fond du Lac
            - "55041"  # Forest
            - "55043"  # Grant
            - "55045"  # Green
            - "55047"  # Green Lake
            - "55049"  # Iowa
            - "55051"  # Iron
            - "55053"  # Jackson
            - "55055"  # Jefferson
            - "55057"  # Juneau
            - "55059"  # Kenosha
            - "55061"  # Kewaunee
            - "55063"  # La Crosse
            - "55065"  # Lafayette
            - "55067"  # Langlade
            - "55069"  # Lincoln
            - "55071"  # Manitowoc
            - "55073"  # Marathon
            - "55075"  # Marinette
            - "55077"  # Marquette
            - "55078"  # Menominee
            - "55079"  # Milwaukee
            - "55081"  # Monroe
            - "55083"  # Oconto
            - "55085"  # Oneida
            - "55087"  # Outagamie
            - "55089"  # Ozaukee
            - "55091"  # Pepin
            - "55093"  # Pierce
            - "55095"  # Polk
            - "55097"  # Portage
            - "55099"  # Price
            - "55101"  # Racine
            - "55103"  # Richland
            - "55105"  # Rock (Janesville)
            - "55107"  # Rusk
            - "55109"  # Saint Croix
            - "55111"  # Sauk
            - "55113"  # Sawyer
            - "55115"  # Shawano
            - "55117"  # Sheboygan
            - "55119"  # Taylor
            - "55121"  # Trempealeau
            - "55123"  # Vernon
            - "55125"  # Vilas
            - "55127"  # Walworth
            - "55129"  # Washburn
            - "55131"  # Washington
            - "55133"  # Waukesha
            - "55135"  # Waupaca
            - "55137"  # Waushara
            - "55139"  # Winnebago (Appleton)
            - "55141"  # Wood
            
      population_estimates:
        name: "Census Population Estimates Program (2019 - Most Recent Available)"
        api_base: "https://api.census.gov/data/2019/pep/population"
        api_key_required: true
        type: "api"
        format: "json"
        update_frequency: "annual"
        release_schedule: "december"
        rate_limit: "unlimited_reasonable_use"
        documentation: "https://www.census.gov/data/developers/data-sets/popest-popproj.html"
        note: "Using 2019 PEP data as 2020+ APIs no longer support county-level queries"
        
        geographic_levels:
          - name: "county"
            code: "050"
            description: "County level population estimates"
            coverage: "all_wisconsin"
        
        target_variables:
          population:
            - variable: "POP"
              name: "population_2019"
              description: "2019 Population Estimate"
          
          demographics:
            - variable: "DENSITY"
              name: "population_density_2019"
              description: "Population Density per Square Mile (2019)"
        
  illinois:
    name: "Illinois"
    fips_code: "17"
    
    business_registrations:
      primary:
        name: "Illinois Secretary of State"
        url: "https://www.cyberdriveillinois.com/departments/business_services/corp.html"
        api_endpoint: "https://www.ilsos.gov/corporatellc/"
        type: "web_scraping"
        format: "html"
        
    sba_loans:
      primary:
        name: "SBA FOIA Data"
        url: "https://www.sba.gov/about-sba/sba-performance/open-government/foia/frequently-requested-records/sba-7a-504-loan-data"
        file_pattern: "7a_504_loans_*_IL_*.csv"
        
    business_licenses:
      chicago:
        name: "Chicago Data Portal"
        url: "https://data.cityofchicago.org/Community-Economic-Development/Business-Licenses/r5kz-chrr"
        api_endpoint: "https://data.cityofchicago.org/resource/r5kz-chrr.json"
        type: "api"
        format: "json"
        app_token_required: true

# Target business types for franchise opportunities
target_business_types:
  high_priority:
    - "restaurant"
    - "food_service"
    - "quick_service_restaurant"
    - "retail_food"
    - "fitness"
    - "personal_services"
    
  medium_priority:
    - "retail"
    - "professional_services"
    - "automotive_services"
    - "health_services"
    - "education_services"
    
  franchise_naics_codes:
    - "722"  # Food services and drinking places
    - "445"  # Food and beverage stores  
    - "448"  # Clothing and clothing accessories
    - "812"  # Personal and laundry services
    - "541"  # Professional services
    - "531"  # Real estate

# Data quality rules
data_quality:
  required_fields:
    business_entity: ["business_name", "city", "state", "business_type"]
    sba_loan: ["borrower_name", "loan_amount", "approval_date"]
    business_license: ["business_name", "license_type", "city", "state"]
    
  validation_rules:
    phone_number: "^\\(?([0-9]{3})\\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$"
    email: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
    zip_code: "^[0-9]{5}(-[0-9]{4})?$"
    state_code: "^[A-Z]{2}$"
    
  confidence_scoring:
    complete_record: 100
    missing_contact_info: 85
    missing_secondary_fields: 70
    minimal_information: 50

# Processing configuration
processing:
  batch_size: 1000
  max_concurrent_requests: 5
  request_timeout_seconds: 30
  retry_attempts: 3
  retry_delay_seconds: 5
  
# BigQuery configuration
bigquery:
  project_id: "location-optimizer-1"
  datasets:
    raw_data: "raw_business_data"
    processed_data: "processed_business_data"
    analytics: "business_analytics"
    
  tables:
    business_entities: "business_entities"
    sba_loans: "sba_loan_approvals"
    business_licenses: "business_licenses"
    opportunity_scores: "opportunity_scores"
    census_demographics: "census_demographics"
    
  partitioning:
    field: "data_extraction_date"
    type: "DAY"
    
  clustering:
    business_entities: ["state", "business_type", "city"]
    sba_loans: ["borrower_state", "approval_date", "program_type"]
    business_licenses: ["state", "city", "license_type"]