name: Weekly DFI Business Collection

on:
  schedule:
    # Run every Sunday at 7:00 AM UTC (adjust timezone as needed)
    - cron: '0 7 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  collect-dfi-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Set up Google Cloud credentials
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > /tmp/gcp-credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json
        
    - name: Run weekly DFI collection
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-credentials.json
      run: |
        cd Business/wisconsin_data_collection
        python3 weekly_dfi_collection.py
        
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: weekly-collection-logs
        path: Business/wisconsin_data_collection/logs/